services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - rag_network

  generation-server:
    image: generation-server:v1.0
    container_name: generation-server
    hostname: generation-server
    restart: always
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - PYTHONUNBUFFERED=1
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - rag_network

  chat:
    image: chat-interface
    container_name: chat-interface
    restart: always
    environment:
      - GENERATION_SERVER_URL=http://generation-server
      - GENERATION_SERVER_PORT=8080
    ports:
      - "8001:8000"
    depends_on:
      - generation-server
    networks:
      - rag_network

networks:
  rag_network:
    name: rag_network
    external: true

volumes:
  mongodb_data:
  chromadb_data: