services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    depends_on: [otel-collector]
    networks:
      - internal
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4318:4318"
      - "4317:4317"
    volumes:
      - ${PWD}/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    networks:
      - internal
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"
    networks:
      - internal
    environment:
      - CHROMA_OPEN_TELEMETRY__ENDPOINT=http://otel-collector:4318/
      - CHROMA_OPEN_TELEMETRY__SERVICE_NAME=chroma
      - IS_PERSISTENT=TRUE
    depends_on:
      - otel-collector
      - zipkin

  generation-server:
    image: generation-server-user-manual:v1.3
    container_name: generation-server
    hostname: generation-server
    restart: always
    environment:
      - COLLECTION_NAME=user-manual
      - MODEL=gpt-4o-mini
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_INTEGRATION=langchain
      - LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_TRACING=true
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - chromadb
    networks:
      - internal

  chat:
    image: chat-interface:v1.1
    container_name: chat-interface
    restart: always
    environment:
      - GENERATION_SERVER_URL=http://generation-server
      - GENERATION_SERVER_PORT=8080
    ports:
      - "8001:8000"
    depends_on:
      - generation-server
    networks:
      - internal


networks:
  internal:

volumes:
  chroma_data: