services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - chroma_data:/data
    ports:
      - "8000:8000"
    networks:
      - internal
    environment:
      - IS_PERSISTENT=TRUE

  generation-server:
    image: generation-server:v1
    container_name: generation-server
    hostname: generation-server
    restart: always
    environment:
      - COLLECTION_NAME=user-manual
      - TEMPLATE_FILE_PATH=/app/templates/system-hr.txt
      - MODEL=gpt-4o-mini
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_INTEGRATION=langchain
      - LANGSMITH_ENDPOINT="https://api.smith.langchain.com"
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}
      - LANGSMITH_TRACING=true
      - MONGODB_URI=mongodb://root:example@mongodb:27017/
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    depends_on:
      - chromadb
    networks:
      - internal

  chat:
    image: chat-interface:latest
    container_name: chat-interface
    restart: always
    environment:
      - GENERATION_SERVER_URL=http://generation-server
      - GENERATION_SERVER_PORT=8080
    ports:
      - "8001:8000"
    depends_on:
      - generation-server
    networks:
      - internal


networks:
  internal:

volumes:
  chroma_data: